# Generated by Django 4.2 on 2026-06-27 15:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee_charged',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=19),
        ),
    ]
