# Generated by Django 4.2 on 2026-07-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_email_verified_user_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='vtype',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('password_reset', 'Password Reset')], max_length=14),
        ),
    ]
