# Generated by Django 4.2 on 2026-06-27 15:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_fee_charged'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_revenue', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Platform Revenue',
                'verbose_name_plural': 'Platform Revenue',
                'db_table': 'platform_revenue',
            },
        ),
    ]
